import LightShow from '@/engine/entities/LightShow';
import { createLinearLightShowSteps } from '@/lib/lights/lights';
import { red } from '../../colors/colors';
import {
	fourTargetGroupTopLight,
	fourTargetGroupFirstFromTopLight,
	fourTargetGroupFirstFromBottomLight,
	fourTargetGroupBottomLight,
	leftRolloverLight,
	leftBonusLight,
	middleBonusLight,
	rightBonusLight,
	rightRolloverLight,
	rightKickerLight,
	topRightKickerLight,
	topRightTargetLight,
	threeTargetGroupRightLight,
	threeTargetGroupCenterLight,
	threeTargetGroupLeftLight,
	topKickerLight,
	topRolloverLight,
	leftTargetLight,
	leftKickerLight,
} from '../../lights/lights';

const debonaireLightShow: LightShow = {
	repeatAfterMilliseconds: 0,
	steps: [
		...createLinearLightShowSteps({
			color: red,
			startTimeInMilliseconds: 0,
			durationInMilliseconds: 1000,
			lights: [
				fourTargetGroupTopLight,
				fourTargetGroupFirstFromTopLight,
				fourTargetGroupFirstFromBottomLight,
				fourTargetGroupBottomLight,
				leftRolloverLight,
				leftBonusLight,
				middleBonusLight,
				rightBonusLight,
				rightRolloverLight,
				rightKickerLight,
				topRightKickerLight,
				topRightTargetLight,
				threeTargetGroupRightLight,
				threeTargetGroupCenterLight,
				threeTargetGroupLeftLight,
				topKickerLight,
				topRolloverLight,
				leftTargetLight,
				leftKickerLight,
			],
		}),
		...createLinearLightShowSteps({
			color: red,
			startTimeInMilliseconds: 500,
			durationInMilliseconds: 1000,
			lights: [
				fourTargetGroupTopLight,
				fourTargetGroupFirstFromTopLight,
				fourTargetGroupFirstFromBottomLight,
				fourTargetGroupBottomLight,
				leftRolloverLight,
				leftBonusLight,
				middleBonusLight,
				rightBonusLight,
				rightRolloverLight,
				rightKickerLight,
				topRightKickerLight,
				topRightTargetLight,
				threeTargetGroupRightLight,
				threeTargetGroupCenterLight,
				threeTargetGroupLeftLight,
				topKickerLight,
				topRolloverLight,
				leftTargetLight,
				leftKickerLight,
			],
		}),
	],
};

export default debonaireLightShow;
